# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela4.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 848)
        MainWindow.setStyleSheet("background-color: #215267;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 710, 1031, 81))
        self.label.setStyleSheet("background-color: #464040;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1031, 81))
        self.label_2.setStyleSheet("background-color: #464040;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_sair = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sair.setGeometry(QtCore.QRect(880, 730, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_sair.setFont(font)
        self.pushButton_sair.setStyleSheet("background-color: rgb(169, 47, 47);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 8px;")
        self.pushButton_sair.setObjectName("pushButton_sair")
        self.label_escolha1 = QtWidgets.QLabel(self.centralwidget)
        self.label_escolha1.setGeometry(QtCore.QRect(180, 260, 171, 241))
        self.label_escolha1.setStyleSheet("background-color: #464040;\n"
"border-radius: 2px;")
        self.label_escolha1.setText("")
        self.label_escolha1.setObjectName("label_escolha1")
        self.pushButton_jogador1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_jogador1.setGeometry(QtCore.QRect(220, 540, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_jogador1.setFont(font)
        self.pushButton_jogador1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;")
        self.pushButton_jogador1.setObjectName("pushButton_jogador1")
        self.label_jogador1 = QtWidgets.QLabel(self.centralwidget)
        self.label_jogador1.setGeometry(QtCore.QRect(170, 200, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_jogador1.setFont(font)
        self.label_jogador1.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_jogador1.setObjectName("label_jogador1")
        self.label_jogador1_pontos = QtWidgets.QLabel(self.centralwidget)
        self.label_jogador1_pontos.setGeometry(QtCore.QRect(310, 200, 41, 31))
        self.label_jogador1_pontos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_jogador1_pontos.setText("")
        self.label_jogador1_pontos.setObjectName("label_jogador1_pontos")
        self.pushButton_jogador2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_jogador2.setGeometry(QtCore.QRect(730, 540, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_jogador2.setFont(font)
        self.pushButton_jogador2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 8px;")
        self.pushButton_jogador2.setObjectName("pushButton_jogador2")
        self.label_jogador2_pontos = QtWidgets.QLabel(self.centralwidget)
        self.label_jogador2_pontos.setGeometry(QtCore.QRect(820, 200, 41, 31))
        self.label_jogador2_pontos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_jogador2_pontos.setText("")
        self.label_jogador2_pontos.setObjectName("label_jogador2_pontos")
        self.label_jogador2 = QtWidgets.QLabel(self.centralwidget)
        self.label_jogador2.setGeometry(QtCore.QRect(680, 200, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_jogador2.setFont(font)
        self.label_jogador2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_jogador2.setObjectName("label_jogador2")
        self.label_escolha2 = QtWidgets.QLabel(self.centralwidget)
        self.label_escolha2.setGeometry(QtCore.QRect(690, 260, 171, 241))
        self.label_escolha2.setStyleSheet("background-color: #464040;\n"
"border-radius: 2px;")
        self.label_escolha2.setText("")
        self.label_escolha2.setObjectName("label_escolha2")
        self.label_empate = QtWidgets.QLabel(self.centralwidget)
        self.label_empate.setGeometry(QtCore.QRect(470, 320, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_empate.setFont(font)
        self.label_empate.setStyleSheet("color: #21D05C;")
        self.label_empate.setObjectName("label_empate")
        self.pushButton_jogar_novamente = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_jogar_novamente.setGeometry(QtCore.QRect(450, 370, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_jogar_novamente.setFont(font)
        self.pushButton_jogar_novamente.setStyleSheet("background-color: #464040;\n"
"color: rgb(255, 255, 255);")
        self.pushButton_jogar_novamente.setCheckable(False)
        self.pushButton_jogar_novamente.setAutoRepeat(False)
        self.pushButton_jogar_novamente.setAutoExclusive(False)
        self.pushButton_jogar_novamente.setObjectName("pushButton_jogar_novamente")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_sair.setText(_translate("MainWindow", "SAIR"))
        self.pushButton_jogador1.setText(_translate("MainWindow", "JOGAR"))
        self.label_jogador1.setText(_translate("MainWindow", "JOGADOR Nº1"))
        self.pushButton_jogador2.setText(_translate("MainWindow", "JOGAR"))
        self.label_jogador2.setText(_translate("MainWindow", "JOGADOR Nº1"))
        self.label_empate.setText(_translate("MainWindow", "EMPATE"))
        self.pushButton_jogar_novamente.setText(_translate("MainWindow", "Jogar novamente"))
